image: node:22

stages:
  - deploy

pages:
  stage: deploy
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules/
  script:
    - npm ci
    - export VITE_BASE_PATH="${VITE_BASE_PATH:-/${CI_PROJECT_NAME}/}"
    - npm run build
    - rm -rf public
    - mv dist public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
